/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void btnExit_click(GButton source, GEvent event) { //_CODE_:btnExit:967411:
  exit();
} //_CODE_:btnExit:967411:

public void btnInfo_click(GButton source, GEvent event) { //_CODE_:btnInfo:828136:
  openInfoWindow();
} //_CODE_:btnInfo:828136:

public void btnNewGame_click(GButton source, GEvent event) { //_CODE_:btnNewGame:852079:
  // Reset the whole canvas
  resetGame();
} //_CODE_:btnNewGame:852079:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  GameView = new GView(this, 200, 0, 1000, 1000, JAVA2D);
  label_lives = new GLabel(this, 50, 18, 100, 50);
  label_lives.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label_lives.setText("LIVES");
  label_lives.setOpaque(false);
  label1 = new GLabel(this, 50, 240, 100, 50);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("POINTS");
  label1.setOpaque(false);
  label2 = new GLabel(this, 50, 468, 100, 50);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("TIME");
  label2.setOpaque(false);
  btnExit = new GButton(this, 50, 930, 100, 50);
  btnExit.setText("EXIT");
  btnExit.setLocalColorScheme(GCScheme.RED_SCHEME);
  btnExit.addEventHandler(this, "btnExit_click");
  LivesView = new GView(this, 0, 96, 200, 50, JAVA2D);
  PointsView = new GView(this, 0, 300, 200, 100, JAVA2D);
  TimeView = new GView(this, 0, 552, 200, 100, JAVA2D);
  btnInfo = new GButton(this, 50, 850, 100, 50);
  btnInfo.setText("INFO");
  btnInfo.addEventHandler(this, "btnInfo_click");
  btnNewGame = new GButton(this, 50, 770, 100, 50);
  btnNewGame.setText("NEW GAME");
  btnNewGame.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  btnNewGame.addEventHandler(this, "btnNewGame_click");
}

// Variable declarations 
// autogenerated do not edit
GView GameView; 
GLabel label_lives; 
GLabel label1; 
GLabel label2; 
GButton btnExit; 
GView LivesView; 
GView PointsView; 
GView TimeView; 
GButton btnInfo; 
GButton btnNewGame; 
